language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
before_install:
  - pip install --upgrade setuptools
  - pip install pytest
# command to install dependencies
install:
  - pip install --editable .
  - pip install aws-adfs['test']
# command to run tests
script: py.test
